[build.environment]
  NPM_VERSION = "latest"

[[redirects]]
  from = "/:slug"
  to = "/.netlify/functions/redirect/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/redirect"
  status = 301
  force = true